# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientServerComms.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x43lientServerComms.proto\x12\x04main\"P\n\rSignUpRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x16\n\x0epublicKeyLogin\x18\x02 \x01(\x0c\x12\x15\n\rpublicKeyChat\x18\x03 \x01(\x0c\"#\n\x0eSignUpResponse\x12\x11\n\tchallenge\x18\x01 \x01(\x0c\"<\n\x1eSignUpChallengeResponseRequest\x12\x1a\n\x12\x63hallenge_response\x18\x01 \x01(\x0c\"!\n\x1fSignUpChallengeResponseResponse\"c\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\x07\x12\x30\n\x10\x64igitalSignature\x18\x03 \x01(\x0b\x32\x16.main.DigitalSignature\"\x0f\n\rLoginResponse\"U\n\x0f\x46indUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x30\n\x10\x64igitalSignature\x18\x02 \x01(\x0b\x32\x16.main.DigitalSignature\"L\n\x10\x46indUserResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\x07\x12\x15\n\rpublicKeyChat\x18\x03 \x01(\x0c\"7\n\x10\x44igitalSignature\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x32\x9d\x02\n\x11\x43lientServerComms\x12\x33\n\x06SignUp\x12\x13.main.SignUpRequest\x1a\x14.main.SignUpResponse\x12\x66\n\x17SignUpChallengeResponse\x12$.main.SignUpChallengeResponseRequest\x1a%.main.SignUpChallengeResponseResponse\x12\x30\n\x05Login\x12\x12.main.LoginRequest\x1a\x13.main.LoginResponse\x12\x39\n\x08\x46indUser\x12\x15.main.FindUserRequest\x1a\x16.main.FindUserResponseB\x18Z\x16securechat-server/grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ClientServerComms_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026securechat-server/grpc'
  _globals['_SIGNUPREQUEST']._serialized_start=33
  _globals['_SIGNUPREQUEST']._serialized_end=113
  _globals['_SIGNUPRESPONSE']._serialized_start=115
  _globals['_SIGNUPRESPONSE']._serialized_end=150
  _globals['_SIGNUPCHALLENGERESPONSEREQUEST']._serialized_start=152
  _globals['_SIGNUPCHALLENGERESPONSEREQUEST']._serialized_end=212
  _globals['_SIGNUPCHALLENGERESPONSERESPONSE']._serialized_start=214
  _globals['_SIGNUPCHALLENGERESPONSERESPONSE']._serialized_end=247
  _globals['_LOGINREQUEST']._serialized_start=249
  _globals['_LOGINREQUEST']._serialized_end=348
  _globals['_LOGINRESPONSE']._serialized_start=350
  _globals['_LOGINRESPONSE']._serialized_end=365
  _globals['_FINDUSERREQUEST']._serialized_start=367
  _globals['_FINDUSERREQUEST']._serialized_end=452
  _globals['_FINDUSERRESPONSE']._serialized_start=454
  _globals['_FINDUSERRESPONSE']._serialized_end=530
  _globals['_DIGITALSIGNATURE']._serialized_start=532
  _globals['_DIGITALSIGNATURE']._serialized_end=587
  _globals['_CLIENTSERVERCOMMS']._serialized_start=590
  _globals['_CLIENTSERVERCOMMS']._serialized_end=875
# @@protoc_insertion_point(module_scope)
