# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ClientServerComms_pb2 as ClientServerComms__pb2


class ClientServerCommsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SignUp = channel.unary_unary(
                '/main.ClientServerComms/SignUp',
                request_serializer=ClientServerComms__pb2.SignUpRequest.SerializeToString,
                response_deserializer=ClientServerComms__pb2.SignUpResponse.FromString,
                )
        self.SignUpChallengeResponse = channel.unary_unary(
                '/main.ClientServerComms/SignUpChallengeResponse',
                request_serializer=ClientServerComms__pb2.SignUpChallengeResponseRequest.SerializeToString,
                response_deserializer=ClientServerComms__pb2.SignUpChallengeResponseResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/main.ClientServerComms/Login',
                request_serializer=ClientServerComms__pb2.LoginRequest.SerializeToString,
                response_deserializer=ClientServerComms__pb2.LoginResponse.FromString,
                )
        self.FindUser = channel.unary_unary(
                '/main.ClientServerComms/FindUser',
                request_serializer=ClientServerComms__pb2.FindUserRequest.SerializeToString,
                response_deserializer=ClientServerComms__pb2.FindUserResponse.FromString,
                )


class ClientServerCommsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SignUp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignUpChallengeResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServerCommsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SignUp': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUp,
                    request_deserializer=ClientServerComms__pb2.SignUpRequest.FromString,
                    response_serializer=ClientServerComms__pb2.SignUpResponse.SerializeToString,
            ),
            'SignUpChallengeResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SignUpChallengeResponse,
                    request_deserializer=ClientServerComms__pb2.SignUpChallengeResponseRequest.FromString,
                    response_serializer=ClientServerComms__pb2.SignUpChallengeResponseResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=ClientServerComms__pb2.LoginRequest.FromString,
                    response_serializer=ClientServerComms__pb2.LoginResponse.SerializeToString,
            ),
            'FindUser': grpc.unary_unary_rpc_method_handler(
                    servicer.FindUser,
                    request_deserializer=ClientServerComms__pb2.FindUserRequest.FromString,
                    response_serializer=ClientServerComms__pb2.FindUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main.ClientServerComms', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientServerComms(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SignUp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.ClientServerComms/SignUp',
            ClientServerComms__pb2.SignUpRequest.SerializeToString,
            ClientServerComms__pb2.SignUpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignUpChallengeResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.ClientServerComms/SignUpChallengeResponse',
            ClientServerComms__pb2.SignUpChallengeResponseRequest.SerializeToString,
            ClientServerComms__pb2.SignUpChallengeResponseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.ClientServerComms/Login',
            ClientServerComms__pb2.LoginRequest.SerializeToString,
            ClientServerComms__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main.ClientServerComms/FindUser',
            ClientServerComms__pb2.FindUserRequest.SerializeToString,
            ClientServerComms__pb2.FindUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
